#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a71

PRODUCT_COPY_FILES += \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ARO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ARO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BKD/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BKD/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BNG/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BNG/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/BVO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/BVO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CHO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CHO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/COO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/COO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/CTI/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/CTI/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/EON/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/EON/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/GTO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/GTO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/INS/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/INS/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/MXO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/MXO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NBP/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NBP/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/NPL/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/NPL/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/OPEN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PEO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PEO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/PSN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/PSN/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLI/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLI/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/SLK/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/SLK/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/TPA/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/TPA/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UFN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UFN/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UPO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UPO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/UYO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/UYO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTA/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTA/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTM/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTM/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTO/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTO/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZTR/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZTR/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/Bluetooth_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/Codec_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/General_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/Global_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/Handset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/Hdmi_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/Headset_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/Speaker_cal.acdb \
    vendor/samsung/a71/proprietary/vendor/etc/audconf/ZVV/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ZVV/workspaceFile.qwsp \
    vendor/samsung/a71/proprietary/vendor/etc/init/init.nfc.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.nfc.samsung.rc \
    vendor/samsung/a71/proprietary/vendor/etc/init/nxp.android.hardware.nfc@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nxp.android.hardware.nfc@1.1-service.rc \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/default_sensors.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm4x6xx_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_ak991x_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_ak991x_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_ak991x_2.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_ak991x_mst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_ak991x_mst_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_ak991x_mst_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_ak991x_mst_2.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_icm4x6xx_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_icm4x6xx_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_icm4x6xx_4.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_power_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_stk3a6x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_stk3a6x_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_stk3x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_stk3x3x_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_tcs3407_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_tcs3407_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sdmmagpie_vcnl36811_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdmmagpie_vcnl36811_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_hw_revision.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_hw_revision.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/stk3a6x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk3a6x_0.json \
    vendor/samsung/a71/proprietary/vendor/etc/sensors/config/vcnl36811_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/vcnl36811_0.json \
    vendor/samsung/a71/proprietary/vendor/firmware/nfc/libpn553_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/libpn553_fw.so \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1s_new.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1s_new.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1s_old.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1s_old.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.sensormodule.0_1_sony_imx682.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.sensormodule.0_1_sony_imx682.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.sensormodule.1_sony_imx616.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.sensormodule.1_sony_imx616.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.sensormodule.2_hynix_hi1336.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.sensormodule.2_hynix_hi1336.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.sensormodule.3_lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.sensormodule.3_lsi_gc5035.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.sensormodule.4_lsi_gc5035_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.sensormodule.4_lsi_gc5035_macro.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.sensormodule.8_sony_imx616_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.sensormodule.8_sony_imx616_full.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.tuned.hynix_hi1336.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.tuned.hynix_hi1336.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.tuned.lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.tuned.lsi_gc5035.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.tuned.lsi_gc5035_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.tuned.lsi_gc5035_macro.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.tuned.lsi_s5kgw1s.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.tuned.lsi_s5kgw1s.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.tuned.sony_imx616.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.tuned.sony_imx616.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/com.samsung.tuned.sony_imx682.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.samsung.tuned.sony_imx682.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/f_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/f_dual_calibration.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/uw_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/uw_dual_calibration.bin \
    vendor/samsung/a71/proprietary/vendor/lib/camera/w_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/w_dual_calibration.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1s_new.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1s_new.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1s_old.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1s_old.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_1_sony_imx682.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_1_sony_imx682.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_sony_imx616.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_sony_imx616.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.sensormodule.2_hynix_hi1336.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.2_hynix_hi1336.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.sensormodule.3_lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.3_lsi_gc5035.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.sensormodule.4_lsi_gc5035_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.4_lsi_gc5035_macro.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.sensormodule.8_sony_imx616_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.8_sony_imx616_full.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.tuned.hynix_hi1336.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.hynix_hi1336.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_gc5035.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_gc5035_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_gc5035_macro.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5kgw1s.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5kgw1s.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx616.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx616.bin \
    vendor/samsung/a71/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx682.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx682.bin

PRODUCT_PACKAGES += \
    com.qti.eeprom.n24s64b_imx616 \
    com.samsung.sensor.gc5035 \
    com.samsung.sensor.gc5035_macro \
    com.samsung.sensor.hi1336 \
    com.samsung.sensor.imx616 \
    com.samsung.sensor.imx682 \
    com.samsung.sensor.s5kgw1s \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.node.depth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.samsung.node.bayercheck \
    com.samsung.node.bayerfuse \
    com.samsung.node.capture_bokeh \
    com.samsung.node.capture_fusion \
    com.samsung.node.realtimebokeh \
    com.samsung.node.remosaic \
    com.samsung.node.smooth_transition \
    com.wrapper.stats.aec \
    com.wrapper.stats.af \
    com.wrapper.stats.awb \
    com.wrapper.stats.pdlib \
    libdepthmapwrapper \
    libmmcamera_cac3 \
    libFacePreProcessing.camera.samsung \
    libbauthserver \
    libbauthtzcommon \
    libegis_fp_normal_sensor_test \
    libgf_in_system_lib \
    libqfp_sensortest \
    libsynaFpSensorTestNwd \
    sensors.grip \
    vendor.qti.hardware.fingerprint@1.0 \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.awb \
    com.qti.stats.haf \
    com.qti.stats.pdlib \
    com.samsung.node.uniplugin_capture \
    com.samsung.node.uniplugin_preview \
    com.samsung.node.uniplugin_recording \
    com.samsung.node.uniplugin_vdis \
    libMOTION \
    libFacialStickerEngine.arcsoft \
    nfc_nci_nxp \
    vendor.nxp.nxpnfc@1.1 \
    factory.ssc \
    nxp.android.hardware.nfc@1.1-service
